services:
  elastichost:
    image: elasticsearch:9.2.2
    environment:
       discovery.type: "single-node" # informamos que o ES será executado em apenas um node
       ES_JAVA_OPTS: "-Xms2g -Xmx2g" # definimos o tamanho minimo e maximo do heap para execução do ES
       xpack.monitoring.enabled: "true" # monitoramente para verificação e comportamento do elasticsearch
       ELASTIC_PASSWORD: "exemplo-minhasenha"
    ports:
      - "9200:9200"
    networks:
      - cineflow
    volumes:
      - elastic:/usr/share/elasticsearch/data
  kibana:
    image: kibana:9.2.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "exemplo-minhasenha"
    networks:
      - cineflow
    depends_on:
      - elastichost
    
    
    
volumes:
  elastic:
    driver: local-persist

networks:
    cineflow:
      driver: bridge